import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Blog from '@/components/Blog'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home(fetchUderInfo) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <div className='mt-14 ml-5'>
<div className="flex">
<div className="text-base ml-10 mr-5 md:mt-[5rem] mt-[4rem] md:ml-14 sm:ml-10 ">
  <h1 className=" text-3xl font-semibold sm:text-3xl  md:text-4xl">Welcome to <span className='font-bold text-green-500'>Mysite</span></h1>
  <p className='py-4 text-gray-500 w-full sm:w-[55%] '>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam ad consectetur molestiae accusamus quibusdam totam exercitationem error assumenda, sapiente distinctio.</p>
<Link href={'/blog'}>
<button className='inline-flex items-center justify-center whitespace-nowrap rounded-md border border-transparent bg-green-500 px-2 py-2 text-base font-medium text-white shadow-sm'>Explore Blog</button>
</Link>
</div>
<div className='h-[100%] md:w-[70%] sm:w-[47%]'>
  <img src="/69091_1.png" className='hidden -ml-[142px] sm:w-[120%] md:block sm:block'  alt="" />
</div>
</div>
   </div>
   <Blog/>
    </>
  )
}
